version: '3.0'
services:
  rasa:
    image: rasa/rasa:2.8.0-full
    ports:
      - "5005:5005"
    volumes:
      - ./:/app
    command:
      - run

  app:
    image: iremozkara/demobot:latest
    expose: [5055]
    
     